---
language: cpp
matrix:
  include:
    # Ubuntu 18.04 + gcc
    - os: linux
      dist: bionic
      compiler: gcc
    # Ubuntu 18.04 + clang
    - os: linux
      dist: bionic
      compiler: clang
    # Ubuntu 16.04 + gcc
    - os: linux
      dist: xenial
      compiler: gcc
    # Ubuntu 16.04 + clang
    - os: linux
      dist: xenial
      compiler: clang
before_install:
  - |
    # For cryptodev-linux
    sudo apt-get -y install "linux-headers-$(uname -r)"

    # For lib842
    sudo apt-get -y install libnuma-dev
    if [[ "$(lsb_release -rs)" == "18.04" ]]; then
      sudo apt-get -y install pocl-opencl-icd opencl-headers ocl-icd-opencl-dev
    fi
script:
  - |
    # Build cryptodev-linux dependency (for using the kernel's 842 support)
    git clone https://github.com/joanbm/cryptodev-linux
    cd cryptodev-linux
    make
    sudo make install
    sudo depmod -a
    sudo modprobe cryptodev
    cd ..

    # Build lib842
    mkdir build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make
    ctest
