language: cpp
matrix:
  include:
  - dist: bionic # Ubuntu 18.04
    compiler: gcc
    os: linux
  - dist: bionic # Ubuntu 18.04
    compiler: clang
    os: linux
  - dist: xenial # Ubuntu 16.04
    compiler: gcc
    os: linux
  - dist: xenial # Ubuntu 16.04
    compiler: clang
    os: linux
before_install:
- sudo apt-get -y install libnuma-dev
- [[ "$(lsb_release -rs)" == "18.04" ]] && sudo apt-get -y install pocl-opencl-icd opencl-headers ocl-icd-opencl-dev
script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- ctest
